# https://www.youtube.com/watch?v=qP8kir2GUgo
variables:
    IMAGE_NAME: docker_repo_name_where_the_image_will_be_pushed
    IMATE_TAG: my_app_tag

stages:
    - test
    - build
    - deploy

run_test:
    stage: test
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get install make
    script:
        - make test
 
build_image:
    stage: build
    image: docker:20.10.16          # includes docker in docker
    services:
        - docker:20.10.16-dind     #docker daemon
    variables:
        DOCKER_TLS_CERTDIR: "/certs" # directorio donde cliente y deamon de docker compartirar certificado
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMATE_TAG .
        - docker push $IMAGE_NAME:$IMATE_TAG
        
deploy:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyCkeching=no -i $SSH_KEY root@161.35.223.117 "
            docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
            docker ps -aq | xargs docker stop | xargs docker rm &&
            docker run -d -p 5000:5000 $IMAGE_NAME:$IMATE_TAG"
        # StrictHostKeyCkeching=no para que no pregunte confirmacion de host desconocido
        # docker ps -a lista todos los containers. -q solo muestra IDs
        # -d (deatach) run container in background
        # -p 5000:5000  -> host_port:container_port (bind port 5000 of the container to port 5000 of the host machine
