#!/bin/sh
# this script is called by pppd when the PPP interface is up
# $1 = interface (e.g. ppp0)

WAN_IFACE="wlp0s20f3" # Set your WAN interface here
PPP_IFACE="$1"

# NAT to allow the PPP client to access the Internet
iptables -t nat -A POSTROUTING -o "$WAN_IFACE" -j MASQUERADE

# Allow traffic from the PPP client to the Internet
iptables -A FORWARD -i "$PPP_IFACE" -o "$WAN_IFACE" -j ACCEPT

# Allow responses from the Internet to the PPP client
iptables -A FORWARD -i "$WAN_IFACE" -o "$PPP_IFACE" -m state --state ESTABLISHED,RELATED -j ACCEPT

