#! /bin/sh

### BEGIN INIT INFO
# Provides:		openfortivpn
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	VPN tunnel
### END INIT INFO

set -e

test -x /usr/bin/openfortivpn || exit 0

. /lib/lsb/init-functions

umask 022

case "$1" in
  start)
	log_daemon_msg "Starting openfortivpn" "openfortivpn" || true
	if start-stop-daemon --start --quiet --background --make-pidfile --oknodo --pidfile /run/openfortivpn.pid --exec /usr/bin/openfortivpn; then
		echo "OK"
		log_end_msg 0 || true
	else
		echo "FAIL"
		log_end_msg 1 || true
	fi
	;;

  stop)
	log_daemon_msg "Stopping openfortivpn" "openfortivpn" || true
	if start-stop-daemon --stop --quiet --remove-pidfile --oknodo --pidfile /run/openfortivpn.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting openfortivpn" "openfortivpn" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /run/openfortivpn.pid
	if start-stop-daemon --start --quiet --oknodo --pidfile /run/openfortivpn.pid --exec /usr/bin/openfortivpn; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  *)
	log_action_msg "Usage: /etc/init.d/openfortivpn {start|stop|restart}" || true
	exit 1
esac

exit 0
